services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    container_name: triton
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    shm_size: "256mb"
    volumes:
      - ./triton/models:/triton/models
    command: >
      tritonserver
      --model-repository=/triton/models
      --log-verbose=1
