services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - ./envs/.minio.env.example
    command: server /data --console-address ":9001"
    networks:
      - my_network

  triton:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    container_name: triton_infer
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    shm_size: "256mb"
    volumes:
      - ./triton_infer/models:/triton_infer/models
    command: >
      tritonserver
      --model-repository=/triton_infer/models
      --log-verbose=1
    networks:
      - my_network

volumes:
  minio_data:

networks:
  my_network:
    driver: bridge
