stages:
  download:
    desc: Download brain MRI dataset from Kaggle
    cmd: bash scripts/download_data.sh
    deps:
      - scripts/download_data.sh
    outs:
      - data/raw

  split:
    desc: split raw dataset into train/val/test
    cmd: uv run python brain_tumor_classification/data/split.py --data_dir data/raw/ --out_dir data/splits/
    deps:
      - brain_tumor_classification/data/split.py
      - data/raw/
    outs:
      - data/splits/

  train_statistics:
    desc: compute mean/std statistics on train split
    cmd: uv run python brain_tumor_classification/data/compute_stats.py --data_dir data/splits/train --out_path data/stats/mean_std.json
    deps:
      - brain_tumor_classification/data/compute_stats.py
      - data/splits/train
    outs:
      - data/stats/

  train:
    desc: Train brain tumor classifier
    cmd: uv run python train.py
    deps:
      - brain_tumor_classification/model.py
      - brain_tumor_classification/data/
      - conf/
      - data/
    outs:
      - checkpoints/

  evaluate:
    desc: Evaluate trained model on test set and compute metrics
    cmd: uv run python brain_tumor_classification/evaluate.py
    deps:
      - brain_tumor_classification/evaluate.py
      - checkpoints/
      - data/splits/test
    outs:
      - results/

  export_onnx:
    desc: Export best model to ONNX
    cmd: uv run python scripts/exports/export_onnx.py
    deps:
      - scripts/export_onnx.py
      - checkpoints/
    outs:
      - artifacts/

  export_tensorrt:
    desc: Convert ONNX model to TensorRT
    cmd: bash scripts/export_tensorrt.sh artifacts/model.onnx
    deps:
      - artifacts/model.onnx
      - scripts/exports/export_tensorrt.sh
    outs:
      - artifacts/model.trt


  create_triton_files:
    desc: Create Triton model repository
    cmd: |
      mkdir -p triton_infer/models/brain_tumor_classification/1 &&
      cp artifacts/model.onnx* triton/models/brain_tumor_classification/1/ &&
      uv run python scripts/make_triton_config.py
    deps:
      - artifacts/model.onnx
      - scripts/make_triton_config.py
    outs:
      - triton_infer/models/brain_tumor_classification/
